routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');
//Route::get('/consultation{token}','ConsultationController@accessConsultaion');
Auth::routes();

Route::group(
    ['middleware' => ['auth']],
    function() {
        Route::group(['namespace' => 'frontend'], function () {
            Route::resource('recensements', 'CitoyenController', ['only' => ['index','create','store','destroy']]);
            Route::get('consultations', 'ConsultationController@consultation')->name('consultations.index');
        });
        Route::resource('visiteurs', 'VisiteurController', ['only' => ['index']]);

    });


Route::group(
    ['namespace' => 'backend'],
    function() {
        Route::resource('visiteurs', 'VisiteurController', ['only' => ['create','index','store']]);
        Route::get('admin', 'DashboardController@admin');
    });

Route::get('password', 'ProfilController@showPasswordForm');
Route::post('/password/update', [
    'as'=>'password.update',
    'uses'=>'ProfilController@updatePassword'
]);

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function admin() {
        return redirect()->route('recensements.index');
    }
}

app/Http/Controllers/backend/VisiteurController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Requests\visiteur\StoreRequest;
use App\Models\Visiteur;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VisiteurController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $visiteurs = Visiteur::all();

        return view('visiteur.index', compact('visiteurs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $visiteur = new Visiteur();
        $title = 'Consultation';
        return view('visiteur.create', compact('visiteur','title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $visiteur = new Visiteur();

        $visiteur->fill($request->except(['_token']));
        if($visiteur->save()) {
            $request->session()->flash('success', 'Vous avez été enregistré parmi les visiteurs du jour avec succès.');
            return redirect()->route('recensements.index');
        } else {
            $request->session()->flash('error', 'Echec! Enregistrement pour visite non-effectué, veuillez réessayer svp.');
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/partials/backend/footer.blade.php
<div class="page-footer">
    <div class="page-footer-inner"> 2017 &copy; SOFIDEV.
        <a href="/" title="Visitez notre site web" target="_blank">Le recensement pour tous !</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

resources/views/partials/backend/header.blade.php
@php
    $currentUser = \Illuminate\Support\Facades\Auth::user();
@endphp
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a style="text-decoration: none;" href="/">
                <h3 class="logo-default" style="font-weight: 500; color: #7FB0DA;">SOFIDEV</h3>
            </a>
            <div class="menu-toggler sidebar-toggler">
                <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN PAGE ACTIONS -->
        <!-- DOC: Remove "hide" class to enable the page header actions -->
        <div class="page-actions">
            <div class="btn-group">
                <button type="button" class="btn red-haze btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <span class="hidden-sm hidden-xs">Bienvenue sur les archives de SOFIDEV</span>
                </button>
            </div>
        </div>
        <!-- END PAGE ACTIONS -->
        <!-- BEGIN PAGE TOP -->
        <div class="page-top">
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <li class="separator hide"> </li>

                    <!-- BEGIN USER LOGIN DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="username username-hide-on-mobile">{{ $currentUser->name }} </span>
                            <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                            <img class="img-circle" src="/uploads/avatars/min/{{$currentUser->avatar}}"  alt=""></a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="/password">
                                    <i class="icon-lock"></i> Mot de passe </a>
                            </li>
                            <li class="divider"> </li>

                            @if(\Illuminate\Support\Facades\Auth::user()->admin)
                            <li>
                                <a href="{{url('/register')}}">
                                    <i class="icon-rocket"></i> Nouveau administrateur </a>
                            </li>
                            @endif
                            <li>
                                <a data-method="POST" href="{{route('logout')}}">
                                    <i class="icon-key"></i> D&eacute;connexion </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->
                    <!-- BEGIN QUICK SIDEBAR TOGGLER -->

                    <!-- END QUICK SIDEBAR TOGGLER -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END PAGE TOP -->
    </div>
    <!-- END HEADER INNER -->
</div>

resources/views/partials/backend/menu.blade.php
    <div class="page-sidebar-wrapper">
        <!-- BEGIN SIDEBAR -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
            <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
            <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
            <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="nav-item start {{ active('home') }} ">
                    <a href="{{ route('home') }}" class="nav-link nav-toggle">
                        <i class="icon-home"></i>
                        <span class="title">Retour à l'accueil</span>
                    </a>
                </li>
                <li class="heading">
                    <h3 class="uppercase">Options</h3>
                </li>
              {{--  <li class="nav-item  {{ active('budget.*') }}">
                    <a href="#" class="nav-link nav-toggle">
                        <i class="icon-wallet"></i>
                        <span class="title">Budgets</span>
                    </a>
                </li>
                <li class="nav-item  {{ active('depense.*') }}">
                    <a href="#" class="nav-link nav-toggle">
                        <i class="icon-bar-chart"></i>
                        <span class="title">Depenses</span>
                    </a>
                </li>--}}
                @if(\Illuminate\Support\Facades\Auth::user()->admin)
                <li class="nav-item  {{ active('visiteurs.*') }}">
                    <a href="{{ route('visiteurs.index') }}" class="nav-link nav-toggle">
                        <i class="icon-user"></i>
                        <span class="title">Visiteurs</span>
                    </a>
                </li>
                @endif
                <li class="nav-item {{ active('recensements.*') }}">
                    <a href="{{ route('recensements.index') }}" class="nav-link nav-toggle">
                        <i class="icon-briefcase"></i>
                        <span class="title">Recensements</span>
                    </a>
                </li>
            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
    </div>

resources/views/partials/backend/statistic.blade.php
<div class="row" id="statisticDashboard">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2 bordered">
            <div class="display">
                <div class="number">
                    <h3 class="font-green-sharp">
                        <span data-counter="counterup" data-value="7800">{{ ($statistic) ? $statistic->budgetRestant : 0 }}</span>
                        <small class="font-green-sharp">F</small>
                    </h3>
                    <small>BUDGET ACTUEL</small>
                </div>
                <div class="icon">
                    <i class="icon-pie-chart"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2 bordered">
            <div class="display">
                <div class="number">
                    <h3 class="font-red-haze">
                        <span data-counter="counterup" data-value="1349">{{ ($statistic) ? $statistic->reglementTotal : 0 }}</span>
                        <small class="font-red-haze">F</small>
                    </h3>
                    <small>REGLEMENTS / Mois</small>
                </div>
                <div class="icon">
                    <i class="icon-bar-chart"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2 bordered">
            <div class="display">
                <div class="number">
                    <h3 class="font-blue-sharp">
                        <span data-counter="counterup" data-value="1349">{{ ($statistic) ? $statistic->achatTotal : 0 }}</span>
                        <small class="font-blue-sharp">F</small>
                    </h3>
                    <small>ACHATS / Mois</small>
                </div>
                <div class="icon">
                    <i class="icon-basket-loaded"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2 bordered">
            <div class="display">
                <div class="number">
                    <h3 class="font-purple-soft">
                        <span data-counter="counterup" data-value="1349">{{ ($statistic) ? $statistic->reliquat : 0 }}</span>
                        <small class="font-purple-soft">F</small>
                    </h3>
                    <small>RELIQUATS </small>
                </div>
                <div class="icon">
                    <i class="icon-cup"></i>
                </div>
            </div>
        </div>
    </div>
</div>