routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');
//Route::get('/consultation{token}','ConsultationController@accessConsultaion');
Auth::routes();

Route::group(
    ['middleware' => ['auth']],
    function() {
        Route::group(['namespace' => 'frontend'], function () {
            Route::resource('recensements', 'CitoyenController', ['only' => ['index','create','store','destroy']]);
            Route::get('consultations', 'ConsultationController@consultation')->name('consultations.index');
        });
        Route::resource('visiteurs', 'VisiteurController', ['only' => ['index']]);

    });


Route::group(
    ['namespace' => 'backend'],
    function() {
        Route::resource('visiteurs', 'VisiteurController', ['only' => ['create','index','store']]);
        Route::get('admin', 'DashboardController@admin');
    });

Route::get('password', 'ProfilController@showPasswordForm');
Route::post('/password/update', [
    'as'=>'password.update',
    'uses'=>'ProfilController@updatePassword'
]);

app/Models/Citoyen.php
<?php

namespace App\Models;

use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\Model;

class Citoyen extends Model
{
    use FormAccessible;

    protected $dates = ['birthday_date'];

    protected $fillable = [
        'first_name',
        'second_name',
        'birthday_date',
        'sex',
        'profession',
        'diplome',
        'residence',
        'telephone',
        'email',
        'village_id',
        'photo'
    ];

    public function village() {
        return $this->belongsTo('App\Models\Village');
    }

    public function getArrondissementNameAttribute() {
        $arrondissement_id = Village::findOrFail($this->getAttribute('village_id'))->arrondissement_id;
        return Arrondissement::find($arrondissement_id)->name;
    }
}

app/Http/Controllers/frontend/CitoyenController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Requests\citoyen\StoreRequest;
use App\Models\Citoyen;
use App\Models\Village;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class CitoyenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $citoyens = Citoyen::with('village')->get();
        $title = 'Recensements';

        return view('citoyen.frontend.index', compact('citoyens','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $citoyen = new Citoyen();
        $title = 'recensements';
        $sex = ['homme','femme'];
        $villages = Village::pluck('name','id')->all();
        return view('citoyen.create', compact('citoyen','title','sex','villages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $citoyen = new Citoyen();

        $citoyen->fill($request->except(['_token']));
        if($request->hasFile('photo'))  {


                $photo = $request->file('photo');

                $filename = uniqid(). '.'.$photo->getClientOriginalExtension();

                Image::make($photo)->save(public_path('uploads/avatars/'.$filename));

                $citoyen->photo = $filename;
        }
        if($citoyen->save()) {
            $request->session()->flash('success', 'Vous avez été recensé avec succès.');
            return redirect()->route('recensements.index');
        } else {
            $request->session()->flash('error', 'Echec! Recensement non effectué, veuillez réessayez svp.');
            return back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Citoyen $citoyen, $id)
    {

        if ($citoyen->findOrFail($id)->delete()) {
            return redirect()->route('recensements.index')->with('message','Citoyen(ne) supprim&eacute; avec succ&egrave;s.');
        }
    }
}

app/Http/Controllers/frontend/ConsultationController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Citoyen;

class ConsultationController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function consultation()
    {
        $citoyens = Citoyen::with('village')->get();
        $title = 'Recensements';

        return view('citoyen.frontend.index', compact('citoyens','title'));
    }
}

resources/views/citoyen/frontend/index.blade.php
@extends('layouts.backend')
@section('content')



    <div class="portlet light bordered">
        <div class="portlet-title">
            <div class="caption font-dark">
                <i class="icon-settings font-dark"></i>
                <span class="caption-subject bold uppercase"> Registre des citoyens et citoyennes recensés. </span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-toolbar">
                <div class="row">
                    @if (Session::has('message'))
                        <div class="alert alert-success">
                            <button class="close" data-close="alert"></button>
                            {{Session::get('message')}}
                        </div>
                    @endif
                    @if (session()->has('message'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ session()->get('message') }}
                        </div>
                    @endif

                    @if (Session::has('error'))
                        <div class="alert alert-danger">
                            <button class="close" data-close="alert"></button>
                            {{Session::get('error')}}
                        </div>
                    @endif
                    <div class="col-md-6 ajout">
                        <div class="btn-group">
                            <a id="sample_editable_1_new" class="btn sbold green" href="{{route('home')}}"> Accueil
                                <i class="fa fa-home"></i>
                            </a>

                        </div>
                    </div>
                    
                    <div class="col-md-6 outils">
                        <div class="btn-group pull-right">
                            <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown">Outils
                                <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li>
                                    <a href="javascript:;" onclick="window.print()">
                                        <i class="fa fa-print"></i> imprimer </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div style="min-height: .01%; overflow-x: auto; width: 100%;">
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                    <thead>
                    <tr>
                        <th class="text-center"> # </th>
                        <th class="text-center"> Nom </th>
                        <th class="text-center"> Prénom </th>
                        <th class="text-center"> Naissance </th>
                        <th class="text-center"> Sexe </th>
                        <th class="text-center"> Profession</th>
                        {{--<th class="text-center"> Diplome </th>--}}
                        <th class="text-center"> Residence </th>
                        <th class="text-center"> téléphone </th>
                        <th class="text-center"> Email </th>
                        <th class="text-center"> Village </th>
                        <th class="text-center"> Arrondissement </th>
                        <th class="text-center"> Photo </th>
                        @if(\Illuminate\Support\Facades\Auth::user()->admin)
                            <th class="text-center"> Action </th>
                        @endif
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($citoyens as $citoyen)
                        <tr class="odd gradeX">
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->id}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->first_name}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->second_name}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->birthday_date->format('d/m/y')}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->sex == 0 ? 'homme' : 'femme'}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->profession}} </td>
                            {{--<td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->diplome}} </td>--}}
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->residence}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->telephone}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->email}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->village->name}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle"> {{$citoyen->village_id ? $citoyen->arrondissement_name : ''}} </td>
                            <td class="text-center" style="display: table-cell; vertical-align: middle">
                                @if($citoyen->photo)


                                    <a href="{{url('uploads/avatars/'.$citoyen->photo)}}"
                                       data-fancybox="gallery"
                                       data-title="Photo de {{$citoyen->first_name}} {{$citoyen->second_name}}">

                                        <img src="{{url('uploads/avatars/'.$citoyen->photo)}}" style="width: 120px; height: 120px;" alt="">

                                    </a>
                                @else
                                    Aucune photo
                                @endif

                            </td>
                            @if(\Illuminate\Support\Facades\Auth::user()->admin)
                                <td class="text-center" style="display: table-cell; vertical-align: middle">

                        <span >
                            <a class="btn btn-xs btn-danger tooltips"
                               href="/recensements/{{$citoyen->id}}"
                               data-method="DELETE"
                               data-confirm="&Ecirc;tes vous s&ugrave;r de vouloir supprimer le / la citoyen(ne) {{$citoyen->first_name .' '. $citoyen->second_name}} du régistre ?"
                               data-title="Confirmation de suppression"
                               data-theme="bootstrap"
                               data-params='{"id": {{$citoyen->id}}}'
                               data-original-title="Supprimer"
                               data-placement="top"
                               data-container ="body">Supprimer
                            </a>

                        </span>
                                </td>
                            @endif
                        </tr>

                    @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>

@stop